name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

jobs:
  deploy-to-dev:
    name: Deploy to Dev Environment
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          echo "Pytest file will eventually run here"

      - name: Deploy to Dev
        env:
          DEV_DEPLOYMENT_TOKEN: ${{ secrets.DEV_DEPLOYMENT_TOKEN }}
        run: |
          echo "Demo Purpose as we don have a separate Dev server"

  deploy-to-prod:
    name: Deploy to Prod Environment
    runs-on: ubuntu-latest
    needs: deploy-to-dev
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: practical-scion-426716-s2
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Decode GCP Service Account Key
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > $HOME/gcp-key.json
      shell: bash

    - name: Authenticate to Google Cloud
      run: |
        gcloud auth activate-service-account --key-file=$HOME/gcp-key.json

    - name: Rolling Update MIG
      run: |
        MIG_NAME=
        INSTANCE_GROUP=instance-group-1
        INSTANCES=$(gcloud compute instance-groups managed list-instances $INSTANCE_GROUP --zone us-east1-b --format=json | jq -r '.[].instance' | awk -F/ '{print $NF}' | paste -sd "," -)
        echo $INSTANCES
        # Recreate instances using the retrieved names
        for instance in $INSTANCES; do
            echo "Recreating instance $instance ..."
            gcloud compute instance-groups managed recreate-instances $INSTANCE_GROUP --instances $instance --zone us-east1-b
            sleep 180
        done  